auteur = "Martin Ouellet"
bloctexte = "center"
copyright = "CC BY-NC-SA"
couverture = "/uploads/couverture.png"
description = "Description"
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = "9782895160243 (2895160244)"
licence = "CC BY-NC-SA"
logo = "images/logo.jpg"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Sous-titre"
titre = "BABEL RAGE"
