auteur = "Martin Ouellet"
bloctexte = "center"
copyright = "CC BY-NC-SA"
couverture = "/uploads/couverture.png"
description = "Martin Ouellet a publié Mourir en rond en 1999 au Éditions TROIS. Babel Rage est son deuxième livre."
edition = "Fabrique"
format = "portrait"
indentation = "non"
isbn = "9782895160243 (2895160244)"
licence = "CC BY-NC-SA"
logo = "themes/roman/layouts/_default/logo.jpg"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = ""
titre = "BABEL RAGE"
